# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Character(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, race: str=None, _class: str=None):  # noqa: E501
        """Character - a model defined in Swagger

        :param name: The name of this Character.  # noqa: E501
        :type name: str
        :param race: The race of this Character.  # noqa: E501
        :type race: str
        :param _class: The _class of this Character.  # noqa: E501
        :type _class: str
        """
        self.swagger_types = {
            'name': str,
            'race': str,
            '_class': str
        }

        self.attribute_map = {
            'name': 'name',
            'race': 'race',
            '_class': 'class'
        }
        self._name = name
        self._race = race
        self.__class = _class

    @classmethod
    def from_dict(cls, dikt) -> 'Character':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Character of this Character.  # noqa: E501
        :rtype: Character
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Character.


        :return: The name of this Character.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Character.


        :param name: The name of this Character.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def race(self) -> str:
        """Gets the race of this Character.


        :return: The race of this Character.
        :rtype: str
        """
        return self._race

    @race.setter
    def race(self, race: str):
        """Sets the race of this Character.


        :param race: The race of this Character.
        :type race: str
        """
        if race is None:
            raise ValueError("Invalid value for `race`, must not be `None`")  # noqa: E501

        self._race = race

    @property
    def _class(self) -> str:
        """Gets the _class of this Character.


        :return: The _class of this Character.
        :rtype: str
        """
        return self.__class

    @_class.setter
    def _class(self, _class: str):
        """Sets the _class of this Character.


        :param _class: The _class of this Character.
        :type _class: str
        """
        if _class is None:
            raise ValueError("Invalid value for `_class`, must not be `None`")  # noqa: E501

        self.__class = _class
