# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EncounterRewards(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, xp: int=None, items: List[str]=None):  # noqa: E501
        """EncounterRewards - a model defined in Swagger

        :param xp: The xp of this EncounterRewards.  # noqa: E501
        :type xp: int
        :param items: The items of this EncounterRewards.  # noqa: E501
        :type items: List[str]
        """
        self.swagger_types = {
            'xp': int,
            'items': List[str]
        }

        self.attribute_map = {
            'xp': 'xp',
            'items': 'items'
        }
        self._xp = xp
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'EncounterRewards':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Encounter_rewards of this EncounterRewards.  # noqa: E501
        :rtype: EncounterRewards
        """
        return util.deserialize_model(dikt, cls)

    @property
    def xp(self) -> int:
        """Gets the xp of this EncounterRewards.


        :return: The xp of this EncounterRewards.
        :rtype: int
        """
        return self._xp

    @xp.setter
    def xp(self, xp: int):
        """Sets the xp of this EncounterRewards.


        :param xp: The xp of this EncounterRewards.
        :type xp: int
        """

        self._xp = xp

    @property
    def items(self) -> List[str]:
        """Gets the items of this EncounterRewards.


        :return: The items of this EncounterRewards.
        :rtype: List[str]
        """
        return self._items

    @items.setter
    def items(self, items: List[str]):
        """Sets the items of this EncounterRewards.


        :param items: The items of this EncounterRewards.
        :type items: List[str]
        """

        self._items = items
